# Generated by Django 3.1.4 on 2020-12-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.CharField(choices=[('Academics', 1), ('Business', 2), ('Design', 3), ('Development', 4), ('Health & Fitness', 5), ('IT & Software', 6), ('language', 7), ('Lifestyle', 8), ('Marketing', 9), ('Music', 10), ('Officer Productivity', 11), ('Personal Development', 12), ('Photography', 13)], max_length=50)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('link', models.CharField(max_length=400)),
                ('tags', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='blog/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
