# Generated by Django 3.1.4 on 2020-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201204_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(choices=[('Academics', 'Academics'), ('Business', 'Business'), ('Design', 'Design'), ('Development', 'Development'), ('Health & Fitness', 'Health & Fitness'), ('IT & Software', 'IT & Software'), ('language', 'language'), ('Lifestyle', 'Lifestyle'), ('Marketing', 'Marketing'), ('Music', 'Music'), ('Officer Productivity', 'Officer Productivity'), ('Personal Development', 'Personal Development'), ('Photography', 'Photography')], max_length=50),
        ),
    ]
