# Generated by Django 3.1.4 on 2020-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201204_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
