# Generated by Django 3.1.4 on 2020-12-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='count',
        ),
    ]
