# Generated by Django 3.1.4 on 2020-12-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
